# Generated by Django 5.2.6 on 2025-10-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0003_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categorie',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
