# Generated by Django 5.2.6 on 2025-10-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categories_categorie_rename_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
