# Generated by Django 5.2.6 on 2025-10-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
