# Generated by Django 5.2.6 on 2025-09-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.products')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.ForeignKey(db_column='order_status_id', on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus'),
        ),
    ]
