# Generated by Django 5.2.6 on 2025-10-06 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(default=0)),
                ('last_assigned_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
