# Generated by Django 5.2.6 on 2025-10-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_quantity_alter_orders_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.ForeignKey(db_column='order_status_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
