# Generated by Django 5.2.6 on 2025-10-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categories_categorie_rename_images_image_and_more'),
        ('orders', '0004_order_alter_orderproduct_order_delete_orders'),
        ('products', '0003_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
